### ISSUE TITLE
Add RU translate

### ISSUE THREAD

**Issue by MuTBu** [RLNT/minecraft_lazierae2#11]
You can add a Russian translation in the new version. I have already sketched out a possible translation beforehand

**Comment by DAmNRelentless** [comment]
The language files are located here: https://github.com/RLNT/minecraft_lazierae2/tree/1.16/src/main/resources/assets/lazierae2/lang

If you want to contribute a Russian translation, feel free to open a pull request.
If you are not sure how to do this or you don't know how to name and format the file correctly, you can also join our support Discord and ask there: https://discord.com/invite/Q3qxws6

We appreciate all contributions!

**Comment by MuTBu** [comment]
complete :)

**Comment by DAmNRelentless** [comment]
https://github.com/RLNT/minecraft_lazierae2/pull/12
