### ISSUE TITLE
Fluix Aggregator and Circuit Etcher cause client crash in a server

### ISSUE THREAD

**Issue by frank89722** [RLNT/minecraft_lazierae2#7]
## Bug Description

As title

## Expected Behavior

Place machine and right-click open GUI

## Current Behavior

Game crash when placed a Fluix Aggregator or Circuit Etcher and can't open GUI on both of them on a server

## Possible Solution

`dev.rlnt.lazierae2.util.GameUtil.getRecipeManager` shouldn't run in client-side

## Reproduction

1. Join a server
2. Placed one of them
3. After rejoining the server still can't open the GUI on both of them 

## Versions

- lazierae2-1.16.5-1.1.1

## Additional Context

Client crashreport: https://gist.github.com/frank89722/2b9dbebf3b210c8dfcc3514fb0f89c88

**Comment by frank89722** [comment]
Jei integration also not work on server.

**Comment by DAmNRelentless** [comment]
Thanks for the report!
