### ISSUE TITLE
Crash when trying put items into Fluix Aggregator and Circuit Etcher

### ISSUE THREAD

**Issue by frank89722** [RLNT/minecraft_lazierae2#8]
## Bug Description

As title, the game crash when trying put items into Fluix Aggregator and Circuit Etcher both cause the client to crash.
Happened in singleplayer and multiplayer.

## Expected Behavior

Making things.

## Current Behavior

Client crash

## Reproduction

1. Open GUI from one of them
2. Put anything in the machine
3. Client crash  

## Versions

- LazierAE2 1.1.2
- AE2 8.3.1

## Additional Context

crash report: https://gist.github.com/frank89722/d053379b9bdaeb45165d75b4c8fe8de0

**Comment by DAmNRelentless** [comment]
Thanks a lot for the report again.
This has now been tested on client and server.

Fixed in https://github.com/RLNT/minecraft_lazierae2/commit/01bc3aac97a592ece9d0799dd161abed436b21b6

**Comment by frank89722** [comment]
Thanks for your quick response and fix too 😄
