### ISSUE TITLE
Add a hotkey to show a summary of what a block does

### ISSUE THREAD

**Issue by Chronophylos** [RLNT/minecraft_lazierae2#9]
## Feature Description

While hovering over an item pressing `SHIFT` will show the amount of upgrades and energy stored.
Add another hotkey like `SHIFT+N` (Mekanism is using that) to display a short summary of what the block does

**Comment by DAmNRelentless** [comment]
I don't really see the reason for that feature.
The usages of the machines are shown in their respective JEI pages.

I am open for discussion what should be written in these tooltips but for now, a feature like that is not planned.

**Comment by Chronophylos** [comment]
ok
